spring:
  application:
    name: ms-inventory
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://mongodb:27017/db-inventory}
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASS:guest}

server:
  port: 8082
